# Generated by Django 2.2 on 2019-05-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='IP del dispositivo donde se originó el reporte', max_length=20)),
                ('descripcion', models.CharField(help_text='Descripción del reporte', max_length=200)),
            ],
        ),
    ]
