# Generated by Django 2.2 on 2019-05-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='fecha',
            field=models.CharField(default=0, help_text='Fecha de registro', max_length=40),
            preserve_default=False,
        ),
    ]
