# Generated by Django 2.2.1 on 2019-05-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(help_text='Fecha de registro', max_length=40)),
                ('ip', models.CharField(help_text='IP del dispositivo origen', max_length=20)),
                ('tipo', models.CharField(help_text='Tipo de estadística', max_length=20)),
                ('valor', models.CharField(help_text='Valor de la estadística', max_length=10)),
            ],
        ),
    ]
