# Generated by Django 2.2.1 on 2019-05-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='fecha',
            field=models.CharField(help_text='Fecha de registro', max_length=40),
        ),
    ]
