# Generated by Django 2.2.1 on 2019-05-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManage', '0002_auto_20190514_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='fecha',
            field=models.DateTimeField(help_text='Fecha de registro', max_length=40),
        ),
    ]
